# Exercise 1.01: Matrix Operations Using NumPy

We will be using Jupyter Notebook and the following matrix to solve this exercise.

We will calculate the square of the matrix, which is determinant of the matrix and the transpose of the matrix shown in the following figure, using NumPy:

![Figure 1.2](img/fig1_02.jpg)

1.- Import the `numpy` library as `np`

In [1]:
# Importando la libreria "numpy" con el prefijo "np"
import numpy as np

2.- Create a two-dimensional array called `A` for storing the $[[1,2,3],[4,5,6],[7,8,9]]$ matrix using `np.mat`, then show de variable A

Output:

```
matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
```

  > If you have created an np.array instead of np.mat, the solution for the array multiplication will be incorrect.

In [2]:
# Creando una matriz de 3x3 con los valores de 1 al 9 usando la función "mat" de la libreria de "numpy" 
A = np.mat([[1,2,3],[4,5,6],[7,8,9]])
A # Mostrando en pantalla

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

3.- Perform matrix multiplication using the asterisk and save the result in a variable called `matmult`

In [3]:
# Realizando la multiplicación por medio de asterisco de matrices y almacenando su valore en la variable "matmult"
matmult = A * A
matmult # Mostrando en pantalla

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

4.- Manually calculate the square of A by performing matrix multiplication. Show the result.

Output:

```
30
```

In [4]:
# De manera manual calculando el cuadrado de la matriz (A*A) 
# multiplicando la primera fila [1,2,3], por la primera columna [1,4,7]
1*1 + 2*4 + 3*7

30

5.- Use `np.linalg.det` to calculate the determinant of the matrix and save the result in a variable called `det`.

Output:

```
0.0
```

In [5]:
# Sacando la determinante de la matriz usando la función "det"
# de la libreria "numpy"
det = np.linalg.det(A)
det # Mostrando en pantalla
# NOTA: Por alguna razón marca un valor no correcto, a mano la determinante de la matriz es 0 (cero)

6.66133814775094e-16

6.- Use `np.matrix.transpose` to get the transpose of the matrix and save the result in a variable called `transpose`

Output:

```
matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
```

In [ ]:
# Sacando la transpuesta de la matriz utilizando la funcion "matrix.transpose" de la libreria "numpy"
transpose = np.matrix.transpose(A)
transpose # Mostrando en pantalla

By completing this exercise, you have seen that NumPy comes with many useful features for vectors, matrices, and other mathematical structures.

In the upcoming section, we will be implementing AI in an interesting tic-tac-toe game using Python.